openapi: 3.0.0
info:
  title: Providing Examples
  description:  Providing Examples
  version: 1.0.0
paths:
  /multiple-examples-in-query-param:
    get:
      tags:
        - Providing Examples
      description: Multiple Examples for querystring parameters
      parameters:  
      - name: 'country-code'
        required: true
        description: Multiple examples. Notice `us` do not have a summary
        in: 'query'
        schema:
          type: 'string'
        examples:
          example1: 
            value: "uk"
            summary: "United Kingdom"
          example2:
            value: "us"
          example3:
            value: "ch"
            summary: "China"
  /multiple-examples-by-response-type:
    get:
      description: Multiple Examples provide for each media-type (`application/json` or `application/json`) 
      tags:
        - Providing Examples
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  age:
                    description: Person Age
                    type: integer
                  fullName:
                    description: Person Full name
                    type: object
                    properties:
                      firstName:
                        description: First name
                        type: string
                      lastName:
                        description: Last name
                        type: string
              examples:
                valid-json:
                  summary: Example with Valid JSON
                  description: If valid JSON is provided in the example, It will be displayed in JSON tree form. Allowing copy/expand/collapse functionality
                  value: |
                    {
                      "person": {
                        "fullName": {
                          "firstName": "Mickey",
                          "lastName": "Mouse"
                        },
                        "age": "9"
                      }
                    }
                invalid-json:
                  summary: Example with Invalid JSON
                  description: Invalid JSON is displayed in text-area as is
                  value: |
                    {
                      person: {
                        fullName: {
                          firstName: Donald,
                          lastName: Duck
                        },
                        age: 10
                      }
                    }
            application/xml:
              schema:
                type: object
                properties:
                  age:
                    description: Person Age
                    type: integer
                  fullName:
                    description: Person Full name
                    type: object
                    properties:
                      firstName:
                        description: First name
                        type: string
                      lastName:
                        description: Last name
                        type: string
              examples:
                example-1:
                  value: |
                    <root>
                      <person>
                        <fullName>
                          <firstName> Mickey </firstName>
                          <lastName> Mouse </lastName>
                        </fullName>
                        <age> 9 </age>
                      </person>
                    </root>
                example-2:
                  value: |
                    <root>
                      <person>
                        <fullName>
                          <firstName> Pluto </firstName>
                        </fullName>
                        <age> 4 </age>
                      </person>
                    </root>

  /single-example-by-response-type:
    get:
      summary: Single Example at schema Level
      tags:
        - Providing Examples
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  age:
                    description: Person Age
                    type: integer
                  fullName:
                    description: Person Full name
                    type: object
                    properties:
                      firstName:
                        description: First name
                        type: string
                      lastName:
                        description: Last name
                        type: string
              example: |
                {
                  age: 10,
                  fullName: {
                    firstName: Donald,
                    lastName: Duck
                  }
                }
  /example-with-array-1:
    get:
      summary: Single Example at schema Level
      tags:
        - Providing Examples
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArrayOfInt-1"
  /example-with-array-2:
    get:
      summary: Single Example at schema Level
      tags:
        - Providing Examples
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArrayOfInt-2"

  /object-example-for-a-schema:
    get:
      summary: Single example having invalid JSON, under a Schema
      tags:
        - Providing Examples
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  age:
                    description: Person Age
                    type: integer
                  fullName:
                    description: Person Full name
                    type: object
                    properties:
                      firstName:
                        description: First name
                        type: string
                      lastName:
                        description: Last name
                        type: string
                example: |
                  {
                    person: {
                      fullName: {
                        firstName: Donald,
                        lastName: Duck
                      },
                      age: 10
                    }
                  }
  /array-example-for-a-schema:
    get:
      summary: Single Example of Type Array Under a Schema
      tags:
        - Providing Examples
      responses:
        '200':
          description: An array of currency codes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/currencies"
  /example-with-simple-object:
    get:
      summary: Single Example of Type Array Under a Schema
      tags:
        - Providing Examples
      responses:
        '200':
          description: An array of currency codes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonObject"
  /per-field-example-with-root-as-object:
    get:
      summary: Field Level example
      tags:
        - Providing Examples
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  age:
                    description: Person Age
                    type: integer
                    example: 8
                  fullName:
                    description: Person Full name
                    type: object
                    properties:
                      firstName:
                        description: First name
                        type: string
                        example: 'Daisy'
                      lastName:
                        description: Last name
                        type: string
                        example: 'Duck'
                  dependents:
                    type: array
                    items:
                      type: object
                      properties:
                        dependentName:
                          type: string
                        relation:
                          type: string
                        age:
                          type: number
  /per-field-example-with-root-as-array:
    get:
      summary: Field Level example
      tags:
        - Providing Examples
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    dependentName:
                      type: string
                    relation:
                      type: string
                    age:
                      type: number
                  example:
                    dependentName: Natasha
                    relation: wife
                    age: 28    
  /example-with-refs:
    get:
      description: |
        When a Schema definition is `provided` as a ref  
        (provide the example at schema-level)
      tags:
        - Providing Examples
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/cost'
              examples:
                USD:
                  description: Cost in `US Dollars`
                  value: |
                    {
                      amount: 10,
                      currency: USD
                    }
                INR:
                  description: Cost in `Indian Rupees`
                  value: |
                    {
                      amount: 700,
                      currency: INR
                    }
  /multiple-example-in-request-body:
    post:
      summary: Request body with multiple examples
      tags:
        - Providing Examples
      requestBody:
        description: Request body containing **multiple** examples
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/cost'
            examples:
              USD:
                description: Cost in `US Dollars`
                value: |
                  {
                    amount: 10,
                    currency: USD
                  }
              INR:
                description: Cost in `Indian Rupees`
                value: |
                  {
                    amount: 700,
                    currency: INR
                  }
components:
  schemas:
    cost:
      type: object
      properties:
        amount:
          type: integer
          description: Amount
        currency:
          description: Currency Code
          type: string
    currencies:
      type: array
      items:
        type: object
        properties:
          currencyCode:
            type: string
          evaluationDate:
            type: string
            format: date-time
      example:
        - currencyCode: USD
          evaluationDate: '2017-07-21T17:32:28Z'
        - currencyCode: INR
          evaluationDate: '2017-07-21T17:32:28Z'
    ArrayOfInt-1:
      type: array
      items:
        type: integer
        format: int64
      example: [1, 2, 3]
    ArrayOfInt-2:
      type: array
      items:
        type: integer
        format: int64
        example: 1
    PersonObject:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
      example:
        name: name-1
        age: 1
