openapi: 3.0.0
info:
  description:  Responses as XML 
  version: 1.0.0
  title: Responses as XML 
paths:
  /xml-response:
    get:
      summary: XML Responses
      description: When response is returned as `xml`, you can provide your own example as `xml - content`
      responses:
        '200':
          description: Successful operation
          content:
            application/xml:
              examples:
                example-1:
                  summary: XML Example
                  value: |
                    <person> 
                      <age>9</age> 
                      <fullName> 
                        <firstName>Mickey</firstName> 
                        <lastName>Mouse</lastName> 
                      </fullName>  
                    </person>
              schema:
                type: object
                properties:
                  age:
                    description: Person Age
                    type: integer
                  fullName:
                    description: Person Full name
                    type: object
                    properties:
                      firstName:
                        description: First name
                        type: string
                      lastName:
                        description: Last name
                        type: string
